### ISSUE TITLE
python-decorator issues

### ISSUE THREAD

**Issue by sjmh** [geerlingguy/packer-centos-7#11]
Appears to be some issues with the CentOS 7 box.

```
[root@salt-master ~]# firewall-cmd
Traceback (most recent call last):
  File "/bin/firewall-cmd", line 32, in <module>
    from firewall.client import *
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 29, in <module>
    import slip.dbus
  File "/usr/lib/python2.7/site-packages/slip/dbus/__init__.py", line 6, in <module>
    import service
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 30, in <module>
    import polkit
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 27, in <module>
    from decorator import decorator
ImportError: No module named decorator
```

A reinstall of certain packages fixes this issue:

```
[root@salt-master ~]# yum reinstall dbus-python pygobject3-base python-decorator python-slip-dbus python-decorator
```

And then:

```
[root@salt-master ~]# firewall-cmd
usage: see firewall-cmd man page
No option specified.
```

**Comment by samh** [comment]
I noticed the same problem with firewalld, and also `ipa-server-install` failed. For that matter, `/usr/bin/pip` still exists, and it fails.

Here are packages with missing files (I think a couple are bogus):

```
[root@ipaserver vagrant]# rpm -Va | grep missing | awk '{ print $2 }' | xargs rpm -qf | sort | uniq
pygobject3-base-3.14.0-3.el7.x86_64
pygpgme-0.3-9.el7.x86_64
pyliblzma-0.5.3-11.el7.x86_64
python-backports-1.0-8.el7.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-decorator-3.4.0-3.el7.noarch
python-iniparse-0.4-9.el7.noarch
python-perf-3.10.0-327.10.1.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64
python-pyudev-0.15-7.el7_2.1.noarch
python-slip-0.4.0-2.el7.noarch
python-slip-dbus-0.4.0-2.el7.noarch
python-urlgrabber-3.10-7.el7.noarch
pyxattr-0.5.1-5.el7.x86_64
wpa_supplicant-2.0-17.el7_1.x86_64
yum-metadata-parser-1.1.4-10.el7.x86_64
```

I'm guessing this is because of the `pip uninstall`. Ansible 2.0 is now in EPEL, if you want to just revert to using that version instead, otherwise you might want to install with pip to somewhere else (virtualenv?).

**Comment by geerlingguy** [comment]
Yeah, it's probably best to just switch to EPEL for the CentOS 7 box, or use Ansible's own repo.

**Comment by bvansomeren** [comment]
Ran into this issue trying to start the tuned service. Reinstalling the affected packages fixes the problem for me. For the next poor soul googling this:  

```
systemctl status tuned.service tuned.service - Dynamic System Tuning Daemon
   Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2016-07-05 19:06:02 UTC; 8s ago
  Process: 12369 ExecStart=/usr/sbin/tuned -l -P (code=exited, status=1/FAILURE)
 Main PID: 12369 (code=exited, status=1/FAILURE)

Jul 05 19:06:02 localhost.localdomain tuned[12369]: from tuned import storage, units, monitors, plugins, profiles, exports, hardware
Jul 05 19:06:02 localhost.localdomain tuned[12369]: File "/usr/lib/python2.7/site-packages/tuned/exports/__init__.py", line 3, in <module>
Jul 05 19:06:02 localhost.localdomain tuned[12369]: import dbus_exporter as dbus
Jul 05 19:06:02 localhost.localdomain tuned[12369]: File "/usr/lib/python2.7/site-packages/tuned/exports/dbus_exporter.py", line 2, in <module>
Jul 05 19:06:02 localhost.localdomain tuned[12369]: import decorator
Jul 05 19:06:02 localhost.localdomain tuned[12369]: ImportError: No module named decorator
```

This was fixed with:

```
yum reinstall dbus-python pygobject3-base python-decorator python-slip-dbus python-decorator python-pyudev
```

**Comment by geerlingguy** [comment]
Sorry about this; I'll try to remember to fix the next time I update the published box on Atlas.

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: geerlingguy/packer-boxes#45
